name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # full checkout (needed for pushing to gh-pages)
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Deploy to the gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
